version: 2
updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - composer
    groups:
      phpstan:
        patterns:
          - "phpstan/*"
      dev-tools:
        patterns:
          - "rector/*"
          - "symplify/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
