language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

env:
 - COMPOSER_OPTIONS=
 - COMPOSER_OPTIONS=--prefer-lowest

before_script:
  - composer install ${COMPOSER_OPTIONS}

script: composer run verify
